/* tslint:disable */
/* eslint-disable */
/**
 * Xiphoo App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-12-23T04:08:23Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagUIDPutModelLocation
 */
export interface TagUIDPutModelLocation {
    /**
     * 
     * @type {number}
     * @memberof TagUIDPutModelLocation
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof TagUIDPutModelLocation
     */
    longitude: number;
}

export function TagUIDPutModelLocationFromJSON(json: any): TagUIDPutModelLocation {
    return TagUIDPutModelLocationFromJSONTyped(json, false);
}

export function TagUIDPutModelLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagUIDPutModelLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function TagUIDPutModelLocationToJSON(value?: TagUIDPutModelLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
    };
}


